// Generated by CoffeeScript 1.9.1
(function() {
  var RecoTw, request;

  request = require('superagent');

  RecoTw = require('../kitchen/recotw');

  RecoTw.setEndpoint = function(endpoint) {
    return RecoTw._endpoint = endpoint;
  };

  RecoTw.setRequester(function(method, api, params) {
    if (typeof Promise === "undefined" || Promise === null) {
      return new Promise.reject('You should require promise or its shim');
    }
    return new Promise(function(done, reject) {
      var req, url;
      url = RecoTw._endpoint + api;
      req = method === 'GET' ? request.get(url).query(params) : request[method.toLowerCase()](url).type('form').send(params);
      return req.set('Accept', 'application/json').end(function(error, res) {
        if (error) {
          return reject(error);
        }
        if (parseInt(res.statusCode, 10) >= 400) {
          return reject({
            error: res.error,
            status: res.statusCode
          });
        }
        return done(res.body);
      });
    });
  });

  module.exports = RecoTw;

}).call(this);
